name: Compile with SourceMod

on:
  push:
    branches: master
  pull_request:
    branches: master
  paths:
    - './color_conf.yaml'
    - './addons/sourcemod/scripting/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: ["1.10", "1.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install curl p7zip-full p7zip-rar

      - name: Set environment variables
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV
          echo "SCRIPTS_PATH=$SOURCEMOD_PATH/scripting" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python3 -m pip install --upgrade pip setuptools wheel

      - name: Clone colorlib-gen
        uses: actions/checkout@v2
        with:
          repository: 'c0rp3n/colorlib-gen'
          ref: 'master'
          path: 'deps/colorlib-gen'

      - name: Install colorlib-gen
        run: |
          pip install -r ./requirements.txt
          python3 ./setup.py install
        working-directory: ./deps/colorlib-gen/

      - name: Generate colorlib_map.inc
        run: colorlib_gen -r --config "./color_conf.yaml" "addons/sourcemod/scripting/include/colorlib_map.inc"

      - name: Compile Plugin
        run: |
          for file in *.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -E -w234 -O2 -v2 -i $SCRIPTS_PATH/include $file
          done
        working-directory: ${{ env.SCRIPTS_PATH }}
